#preload = ~/.config/backgrounds/shaded.png
#wallpaper = , ~/.config/backgrounds/shaded.png
wallpaper {
    monitor = 
    path = ~/.config/backgrounds/shaded.png
    fit_mode = cover
}

#preload {
#    monitor = 
#    path = ~/.config/backgrounds/shaded.png
#    fit_mode = cover
#}
splash = false
